------------------------
-- 1.在 boss 库执行
------------------------

-- 删除用户级权限
DELETE FROM DATABANK.TBL_DB_USER_ROLE
WHERE ROLE_ID IN (
  SELECT
    ROLE_ID
  FROM DATABANK.TBL_DB_ROLE
  WHERE ROLE_TYPE = '0'
);
DELETE FROM DATABANK.TBL_DB_ROLE
WHERE ROLE_TYPE = '0';
ALTER TABLE DATABANK.TBL_DB_ROLE DROP ROLE_TYPE;

-- 记忆用户上一次使用的数据源
ALTER TABLE DATABANK.TBL_DB_USER ADD LAST_DS INT;
ALTER TABLE DATABANK.TBL_DB_USER ADD CONSTRAINT LAST_DS CHECK (LAST_DS IS NOT NULL);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DATABANK.TBL_DB_USER');

-- 查询日志迁移
RENAME TABLE DATABANK.TBL_DB_LOG TO TBL_DB_LOG2;
CREATE TABLE DATABANK.TBL_DB_LOG
(
  LOG_ID               BIGINT PRIMARY KEY NOT NULL,
  LOG_EXECUTOR         VARCHAR(40)        NOT NULL,
  LOG_DS_ID            BIGINT             NOT NULL,
  LOG_QUERY            VARCHAR(10240)     NOT NULL,
  LOG_LEVEL            VARCHAR(10)        NOT NULL,
  LOG_STATUS           SMALLINT           NOT NULL,
  LOG_SCORE            INT                NOT NULL,
  LOG_START_DATETIME   TIMESTAMP          NOT NULL,
  LOG_USED_MILLISECOND BIGINT             NOT NULL
);
INSERT INTO DATABANK.TBL_DB_LOG (LOG_ID, LOG_EXECUTOR, LOG_DS_ID, LOG_QUERY, LOG_LEVEL, LOG_STATUS, LOG_SCORE, LOG_START_DATETIME, LOG_USED_MILLISECOND)
  (SELECT
     LOG_ID,
     LOG_EXECUTOR,
     LOG_DS_ID,
     cast(LOG_QUERY AS VARCHAR(10240)),
     LOG_LEVEL,
     LOG_STATUS,
     LOG_SCORE,
     LOG_START_DATETIME,
     LOG_USED_MILLISECOND
   FROM DATABANK.TBL_DB_LOG2);
DROP TABLE DATABANK.TBL_DB_LOG2;

-- 查询笔记迁移
RENAME TABLE DATABANK.TBL_DB_NOTE TO TBL_DB_NOTE2;
CREATE TABLE DATABANK.TBL_DB_NOTE
(
  NOTE_ID            BIGINT PRIMARY KEY NOT NULL,
  NOTE_NAME          VARCHAR(80)        NOT NULL,
  NOTE_DS_ID         BIGINT             NOT NULL,
  NOTE_QUERY         VARCHAR(10240)     NOT NULL,
  NOTE_USED_TIMES    BIGINT             NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  CREATED_DATE       TIMESTAMP          NOT NULL
);
INSERT INTO DATABANK.TBL_DB_NOTE (NOTE_ID, NOTE_NAME, NOTE_DS_ID, NOTE_QUERY, NOTE_USED_TIMES, LAST_MODIFIED_DATE, CREATED_DATE)
  (SELECT
     NOTE_ID,
     NOTE_NAME,
     NOTE_DS_ID,
     cast(NOTE_QUERY AS VARCHAR(10240)),
     NOTE_USED_TIMES,
     LAST_MODIFIED_DATE,
     CREATED_DATE
   FROM DATABANK.TBL_DB_NOTE2);
DROP TABLE DATABANK.TBL_DB_NOTE2;
