------------------------
-- 1.在 boss 库执行
------------------------
-- 数据源相关
DROP SEQUENCE DATABANK.SEQ_DS;
CREATE SEQUENCE DATABANK.SEQ_DS
AS INTEGER
START WITH 10
INCREMENT BY 1
CYCLE
CACHE 20;

DROP TABLE DATABANK.TBL_DB_DATASOURCE;
CREATE TABLE DATABANK.TBL_DB_DATASOURCE
(
  DS_ID              BIGINT PRIMARY KEY NOT NULL,
  DS_NAME            VARCHAR(40)        NOT NULL,
  DB_TYPE            VARCHAR(10)        NOT NULL,
  DS_CONN_STR        VARCHAR(80)        NOT NULL,
  DS_USERNAME        VARCHAR(40)        NOT NULL,
  DS_PASSWORD        VARCHAR(40)        NOT NULL,
  DS_DESCRIPTION     VARCHAR(255)       NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP,
  CREATED_DATE       TIMESTAMP
);
ALTER TABLE DATABANK.TBL_DB_DATASOURCE
ADD CONSTRAINT unique_ds_name UNIQUE (DS_NAME);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DATABANK.TBL_DB_DATASOURCE');

-- 日志相关
DROP SEQUENCE DATABANK.SEQ_LOG;
CREATE SEQUENCE DATABANK.SEQ_LOG
AS INTEGER
START WITH 10
INCREMENT BY 1
CYCLE
CACHE 20;

DROP TABLE DATABANK.TBL_DB_LOG;
CREATE TABLE DATABANK.TBL_DB_LOG
(
  LOG_ID               BIGINT PRIMARY KEY NOT NULL,
  LOG_EXECUTOR         VARCHAR(40)        NOT NULL,
  LOG_DS_ID            BIGINT             NOT NULL,
  LOG_QUERY            CLOB               NOT NULL,
  LOG_LEVEL            VARCHAR(10)        NOT NULL,
  LOG_STATUS           SMALLINT           NOT NULL,
  LOG_SCORE            INT                NOT NULL,
  LOG_START_DATETIME   TIMESTAMP          NOT NULL,
  LOG_USED_MILLISECOND BIGINT             NOT NULL
);


-- 用户权限相关
DROP TABLE DATABANK.TBL_DB_USER;
CREATE TABLE DATABANK.TBL_DB_USER
(
  USER_ID            BIGINT PRIMARY KEY NOT NULL,
  LOGIN_NAME         VARCHAR(40)        NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  CREATED_DATE       TIMESTAMP          NOT NULL
);

DROP SEQUENCE DATABANK.SEQ_ROLE;
CREATE SEQUENCE DATABANK.SEQ_ROLE
AS INTEGER
START WITH 10
INCREMENT BY 1
CYCLE
CACHE 20;

DROP TABLE DATABANK.TBL_DB_ROLE;
CREATE TABLE DATABANK.TBL_DB_ROLE
(
  ROLE_ID     BIGINT PRIMARY KEY NOT NULL,
  ROLE_NAME   VARCHAR(40)        NOT NULL,
  PERMISSIONS VARCHAR(255),
  ROLE_TYPE   VARCHAR(1)         NOT NULL
);
ALTER TABLE DATABANK.TBL_DB_ROLE
ADD CONSTRAINT unique_role_name UNIQUE (ROLE_NAME);
CALL SYSPROC.ADMIN_CMD('REORG TABLE DATABANK.TBL_DB_ROLE');

DROP TABLE DATABANK.TBL_DB_USER_ROLE;
CREATE TABLE DATABANK.TBL_DB_USER_ROLE
(
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL
);


-- 笔记相关
DROP SEQUENCE DATABANK.SEQ_NOTE;
CREATE SEQUENCE DATABANK.SEQ_NOTE
AS INTEGER
START WITH 10
INCREMENT BY 1
CYCLE
CACHE 20;

DROP TABLE DATABANK.TBL_DB_NOTE;
CREATE TABLE DATABANK.TBL_DB_NOTE
(
  NOTE_ID            BIGINT PRIMARY KEY NOT NULL,
  NOTE_NAME          VARCHAR(80)        NOT NULL,
  NOTE_DS_ID         BIGINT             NOT NULL,
  NOTE_QUERY         CLOB               NOT NULL,
  NOTE_USED_TIMES    BIGINT             NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP          NOT NULL,
  CREATED_DATE       TIMESTAMP          NOT NULL
);
DROP TABLE DATABANK.TBL_DB_USER_NOTE;
CREATE TABLE DATABANK.TBL_DB_USER_NOTE
(
  USER_ID BIGINT NOT NULL,
  NOTE_ID BIGINT NOT NULL
);


------------------------
-- 2.以下为运营后台数据库需要添加的菜单和权限
------------------------
DELETE FROM EMP.TBL_FUNCTION
WHERE FUNCTIONID BETWEEN -339999 AND -330000;
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330001, '[数据银行]导入用户', 'https://boss3g.yeepay.com/databank-boss/user/createForm.action', -99910033, 'ACTIVE', '创建用户', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330002, '[数据银行]导入用户入口', 'https://boss3g.yeepay.com/databank-boss/user/create.action', -99910033, 'ACTIVE', '创建用户入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330003, '[数据银行]更新用户', 'https://boss3g.yeepay.com/databank-boss/user/updateForm.action', -99910033, 'ACTIVE', '更新用户', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330004, '[数据银行]更新用户入口', 'https://boss3g.yeepay.com/databank-boss/user/update.action', -99910033, 'ACTIVE', '更新用户入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330005, '[数据银行]用户列表', 'https://boss3g.yeepay.com/databank-boss/user/list.action', -99910033, 'ACTIVE', '用户列表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330006, '[数据银行]删除用户', 'https://boss3g.yeepay.com/databank-boss/user/delete.action', -99910033, 'ACTIVE', '删除用户', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330007, '[数据银行]创建角色', 'https://boss3g.yeepay.com/databank-boss/role/createForm.action', -99910033, 'ACTIVE', '创建角色', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330008, '[数据银行]创建角色入口', 'https://boss3g.yeepay.com/databank-boss/role/create.action', -99910033, 'ACTIVE', '创建角色入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330009, '[数据银行]更新角色', 'https://boss3g.yeepay.com/databank-boss/role/updateForm.action', -99910033, 'ACTIVE', '更新角色', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330010, '[数据银行]更新角色入口', 'https://boss3g.yeepay.com/databank-boss/role/update.action', -99910033, 'ACTIVE', '更新角色入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330011, '[数据银行]角色列表', 'https://boss3g.yeepay.com/databank-boss/role/list.action', -99910033, 'ACTIVE', '角色列表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330012, '[数据银行]删除角色', 'https://boss3g.yeepay.com/databank-boss/role/delete.action', -99910033, 'ACTIVE', '删除角色', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330013, '[数据银行]创建数据源', 'https://boss3g.yeepay.com/databank-boss/datasource/createForm.action', -99910033, 'ACTIVE', '创建数据源', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330014, '[数据银行]创建数据源入口', 'https://boss3g.yeepay.com/databank-boss/datasource/create.action', -99910033, 'ACTIVE', '创建数据源入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330015, '[数据银行]更新数据源', 'https://boss3g.yeepay.com/databank-boss/datasource/updateForm.action', -99910033, 'ACTIVE', '更新数据源', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330016, '[数据银行]更新数据源入口', 'https://boss3g.yeepay.com/databank-boss/datasource/update.action', -99910033, 'ACTIVE', '更新数据源入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330017, '[数据银行]数据源列表', 'https://boss3g.yeepay.com/databank-boss/datasource/list.action', -99910033, 'ACTIVE', '数据源列表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330018, '[数据银行]删除数据源', 'https://boss3g.yeepay.com/databank-boss/datasource/delete.action', -99910033, 'ACTIVE', '删除数据源', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330019, '[数据银行]按环境获取数据源', 'https://boss3g.yeepay.com/databank-boss/datasource/listByEnvType.action', -99910033, 'ACTIVE', '按环境获取数据源', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330020, '[数据银行]验证数据源', 'https://boss3g.yeepay.com/databank-boss/datasource/verify.action', -99910033, 'ACTIVE', '验证数据源', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330021, '[数据银行]查看日志', 'https://boss3g.yeepay.com/databank-boss/log/list.action', -99910033, 'ACTIVE', '查看日志', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330022, '[数据银行]创建报表', 'https://boss3g.yeepay.com/databank-boss/report/createForm.action', -99910033, 'ACTIVE', '创建报表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330023, '[数据银行]创建报表入口', 'https://boss3g.yeepay.com/databank-boss/report/create.action', -99910033, 'ACTIVE', '创建报表入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330024, '[数据银行]更新报表', 'https://boss3g.yeepay.com/databank-boss/report/updateForm.action', -99910033, 'ACTIVE', '更新报表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330025, '[数据银行]更新报表入口', 'https://boss3g.yeepay.com/databank-boss/report/update.action', -99910033, 'ACTIVE', '更新报表入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330026, '[数据银行]报表列表', 'https://boss3g.yeepay.com/databank-boss/report/list.action', -99910033, 'ACTIVE', '报表列表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330027, '[数据银行]删除报表', 'https://boss3g.yeepay.com/databank-boss/report/delete.action', -99910033, 'ACTIVE', '删除报表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330028, '[数据银行]快速查询', 'https://boss3g.yeepay.com/databank-boss/query/queryForm.action', -99910033, 'ACTIVE', '快速查询', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330029, '[数据银行]快速查询入口', 'https://boss3g.yeepay.com/databank-boss/query/query.action', -99910033, 'ACTIVE', '快速查询入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330030, '[数据银行]验证查询', 'https://boss3g.yeepay.com/databank-boss/query/verify.action', -99910033, 'ACTIVE', '验证查询', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330031, '[数据银行]查询部门用户', 'https://boss3g.yeepay.com/databank-boss/user/userList.action', -99910033, 'ACTIVE', '查询部门用户', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330032, '[数据银行]查询用户信息', 'https://boss3g.yeepay.com/databank-boss/user/userInfo.action', -99910033, 'ACTIVE', '查询用户信息', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330033, '[数据银行]创建笔记', 'https://boss3g.yeepay.com/databank-boss/note/create.action', -99910033, 'ACTIVE', '创建笔记', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
--INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330034, '[数据银行]更新笔记', 'https://boss3g.yeepay.com/databank-boss/note/updateForm.action', -99910033, 'ACTIVE', '更新笔记', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330035, '[数据银行]更新笔记入口', 'https://boss3g.yeepay.com/databank-boss/note/update.action', -99910033, 'ACTIVE', '更新笔记入口', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330036, '[数据银行]笔记列表', 'https://boss3g.yeepay.com/databank-boss/note/list.action', -99910033, 'ACTIVE', '笔记列表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330037, '[数据银行]删除笔记', 'https://boss3g.yeepay.com/databank-boss/note/delete.action', -99910033, 'ACTIVE', '删除笔记', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME, CHECKFUNCTIONID, CHECKNEEDED, LOGNEEDED) VALUES (-330038, '[数据银行]下载报表', 'https://boss3g.yeepay.com/databank-boss/query/down.action', -99910033, 'ACTIVE', '下载报表', 'MIDDLE', 'DEPARTMENT_PRIVATE', CURRENT_TIMESTAMP, null, null, null);

DELETE FROM EMP.TBL_ROLEANDFUNCTIONRELATION
WHERE ROLEID = 161 AND FUNCTIONID BETWEEN -339999 AND -330000;
INSERT INTO EMP.TBL_ROLEANDFUNCTIONRELATION (ROLEID, FUNCTIONID) SELECT
                                                                   161,
                                                                   FUNCTIONID
                                                                 FROM EMP.TBL_FUNCTION
                                                                 WHERE FUNCTIONID BETWEEN -330038 AND -330000;

-- 设置虚拟分组
DELETE FROM EMP.TBL_FUNCTION
WHERE FUNCTIONID = -99910033;
INSERT INTO EMP.TBL_FUNCTION (FUNCTIONID, FUNCTIONNAME, FUNCTIONURL, PREFUNCTIONID, FUNCTIONSTATUS, DESCRIPTION, RISKLEVEL, FUNCTIONTYPE, CREATETIME) VALUES (-99910033, '数据银行', NULL, NULL, 'ACTIVE', '-339999管理分组', 'MIDDLE', NULL, CURRENT TIMESTAMP);
DELETE FROM EMP.TBL_ROLEANDFUNCTIONRELATION
WHERE FUNCTIONID = -99910033;
INSERT INTO EMP.TBL_ROLEANDFUNCTIONRELATION (ROLEID, FUNCTIONID) SELECT
                                                                   A.ROLEID,
                                                                   -99910033
                                                                 FROM EMP.TBL_ROLE A
                                                                 WHERE EXISTS(SELECT
                                                                                *
                                                                              FROM EMP.TBL_ROLEANDFUNCTIONRELATION C,
                                                                                EMP.TBL_FUNCTION D
                                                                              WHERE A.ROLEID = C.ROLEID AND
                                                                                    C.FUNCTIONID = D.FUNCTIONID AND
                                                                                    D.PREFUNCTIONID = -99910033);

-- 部门功能关系表
DELETE FROM EMP.TBL_DEPARTMENTANDFUNCTIONRELATION
WHERE DEPARTMENTID = -2 AND FUNCTIONID BETWEEN -339999 AND -330000 OR FUNCTIONID = -99910033;
INSERT INTO EMP.TBL_DEPARTMENTANDFUNCTIONRELATION (DEPARTMENTID, FUNCTIONID) SELECT
                                                                               -2,
                                                                               FUNCTIONID
                                                                             FROM EMP.TBL_FUNCTION
                                                                             WHERE
                                                                               FUNCTIONID BETWEEN -330038 AND -330000 OR
                                                                               FUNCTIONID = -99910033;

-- 菜单
DELETE FROM EMP.TBL_MENU
WHERE MENUID BETWEEN -339999 AND -330000 OR MENUID BETWEEN -3301 AND -3301 OR MENUID = -1033;
INSERT INTO EMP.TBL_MENU (MENUID, MENUNAME, FUNCTIONID, SEQUENCE, PARENTID, LEVELNUM, ICONNAME) VALUES
(-3301, '数据银行', -1, 33, -1, 2, '/css/common/img/menu/ico1.gif'),
(-330001, '导入用户', -330001, 1, -3301, 3, null),
(-330002, '用户列表', -330005, 2, -3301, 3, null),
(-330003, '创建角色', -330007, 3, -3301, 3, null),
(-330004, '角色列表', -330011, 4, -3301, 3, null),
(-330005, '创建数据源', -330013, 5, -3301, 3, null),
(-330006, '数据源列表', -330017, 6, -3301, 3, null),
(-330007, '查看日志', -330021, 7, -3301, 3, null),
(-330008, '快速查询', -330028, 8, -3301, 3, null),
(-330009, '笔记列表', -330036, 9, -3301, 3, null);
